require("plugs.navi") -- for navigation between panes
require("plugs.tele")
require("plugs.pairs")
require("plugs.comments")
require("plugs.colors")
require("plugs.folds")
require("plugs.snips")
require("plugs.tree")
require("plugs.cmp")
require("plugs.lsp")
require("plugs.null_ls")
require("plugs.noice")
require("plugs.whichkey")
require("plugs.todo")
require("plugs.lualine")
require("plugs.gitsigns")
require("plugs.toggleterm")
require("plugs.startup")
